---
- name: Add Password to Passwork and Change Root Password on Remote Servers
  hosts: servers
  become: yes
  gather_facts: no
  vars:
    passwork_api_url: "https://passwork.eurostil.ru/api/v4"
    passwork_api_token: "{{ lookup('env', 'PASSWORK_API_TOKEN') }}"
    passwork_category_id: 1
    passwork_record_title: "Root Password for {{ inventory_hostname }}"
    new_password_length: 16
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure custom modules are available
      copy:
        src: ../library/passwork_add_password.py
        dest: /tmp/passwork_add_password.py
        mode: '0755'

    - name: Add new password using custom module
      ansible.builtin.command:
        cmd: "/usr/bin/python3 /tmp/passwork_add_password.py api_url={{ passwork_api_url }} api_token={{ passwork_api_token }} record_title='{{ passwork_record_title }}' category_id={{ passwork_category_id }} password_length={{ new_password_length }}"
      register: passwork_result

    - name: Set new root password
      ansible.builtin.shell:
        cmd: "echo -e '{{ passwork_result.stdout.split(': ')[1] }}\n{{ passwork_result.stdout.split(': ')[1] }}' | passwd"
      args:
        warn: no

    - name: Display new password
      ansible.builtin.debug:
        msg: "New password for {{ inventory_hostname }} is {{ passwork_result.stdout.split(': ')[1] }}"